### PR TITLE
removing dangerous files

### PR DESCRIPTION
**Pull request by bhrdn**

### CODE REVIEW

**Comment by ammarfaizi2** [comment]
I could see that `shell.php` is a very very dangerous file. Especially I ran my web server and php-fpm as root. But, in our VPC (Virtual Private Cloud) we need this file to performing some shell commands execution.

For this case, I only approve a pull request that make it more secure, not to remove this feature, like give some auth to this one.

Any suggesstion related to this issue will be appreciated.

**Review by ammarfaizi2 — CHANGES_REQUESTED** [review]
We need this file in our VPC.

**Comment by LIQRGV** [comment]
Maybe we can restrict which operation is permitted.
Or else, add more security layer like encrypted command, maybe?

**Comment by bhrdn** [comment]
> I could see that `shell.php` is a very very dangerous file. Especially I ran my web server and php-fpm as root. But, in our VPC (Virtual Private Network) we need this file to performing some shell commands execution.
> 
> For this case, I only approve a pull request that make it more secure, not to remove this feature, like give some auth to this one.
> 
> Any suggesstion related to this issue will be appreciated.

hmm i see.. maybe u can use https://github.com/b374k/b374k to make it safer :sweat_smile:
btw follback dong pak ammar.. :satisfied: :satisfied:

**Comment by ammarfaizi2** [comment]
@LIQRGV I prefer to use token or password instead of encrypted command. But yeah we only use this in private network. So we do not worry our app to be hacked.

@bhrdn We need an API shell instead of web shell, so we cannot use b374k in this case.

**Comment by ammarfaizi2** [comment]
@bhrdn Ok, followed.

**Comment by codenoid** [comment]
O W O
PUB

**Pull request closed without merging**
